### PR TITLE
Fix Brass dust and Silver ore smelting

### PR DESCRIPTION
**Pull request by Alan19**
DT silver ore is hardcoded to smelt into DT silver ingot, but I've fixed the rest of the silver ores.

I also made brass dust smelt into brass ingots instead of alchemical brass

### CODE REVIEW

**Comment by Alan19** [comment]
Is the way I'm removing the furnace recipe is okay?

**Comment by Alan19** [comment]
The Erebus ores still smelt into the Erebus ingots.

**Comment by belathus** [comment]
I'd prefer to fix the silver recipe through the recipe functions I wrote, but this'll do for now. I fixed the brass furnace recipe (and possibly other recipes) through commit https://github.com/belathus/Wanderlust-Renewed/commit/0b9f18a6b565bd6046974ae8d7ea661ddc61aeb9. Not sure why you fixed the crushed dark gem typo in this pull request. :P

**Comment by Alan19** [comment]
I've removed the other files from the pull request.

**Comment by Alan19** [comment]
You probably want to use squash and merge

**Pull request merged**
